In [34]:
import pandas as pd
df = pd.read_csv('titanic.csv')

In [35]:
df

PassengerId                                               Name  Pclass  \
0              1                            Braund, Mr. Owen Harris       3   
1              2  Cumings, Mrs. John Bradley (Florence Briggs Th...       1   
2              3                             Heikkinen, Miss. Laina       3   
3              4       Futrelle, Mrs. Jacques Heath (Lily May Peel)       1   
4              5                           Allen, Mr. William Henry       3   
..           ...                                                ...     ...   
886          887                              Montvila, Rev. Juozas       2   
887          888                       Graham, Miss. Margaret Edith       1   
888          889           Johnston, Miss. Catherine Helen "Carrie"       3   
889          890                              Behr, Mr. Karl Howell       1   
890          891                                Dooley, Mr. Patrick       3   

        Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  \
0      male  22.0      1      0         A/5 21171   7.2500   NaN        S   
1    female  38.0      1      0          PC 17599  71.2833   C85        C   
2    female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S   
3    female  35.0      1      0            113803  53.1000  C123        S   
4      male  35.0      0      0            373450   8.0500   NaN        S   
..      ...   ...    ...    ...               ...      ...   ...      ...   
886    male  27.0      0      0            211536  13.0000   NaN        S   
887  female  19.0      0      0            112053  30.0000   B42        S   
888  female   NaN      1      2        W./C. 6607  23.4500   NaN        S   
889    male  26.0      0      0            111369  30.0000  C148        C   
890    male  32.0      0      0            370376   7.7500   NaN        Q   

     Survived  
0           0  
1           1  
2           1  
3           1  
4           0  
..        ...  
886         0  
887         1  
888         0  
889         1  
890         0  

[891 rows x 12 columns]

In [36]:
df.head()

PassengerId                                               Name  Pclass  \
0            1                            Braund, Mr. Owen Harris       3   
1            2  Cumings, Mrs. John Bradley (Florence Briggs Th...       1   
2            3                             Heikkinen, Miss. Laina       3   
3            4       Futrelle, Mrs. Jacques Heath (Lily May Peel)       1   
4            5                           Allen, Mr. William Henry       3   

      Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  \
0    male  22.0      1      0         A/5 21171   7.2500   NaN        S   
1  female  38.0      1      0          PC 17599  71.2833   C85        C   
2  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S   
3  female  35.0      1      0            113803  53.1000  C123        S   
4    male  35.0      0      0            373450   8.0500   NaN        S   

   Survived  
0         0  
1         1  
2         1  
3         1  
4         0

In [37]:
df.drop(['PassengerId', 'Name', 'Pclass', 'Parch', 'Ticket', 'Cabin', 'Embarked'], axis= 'columns', inplace=True)

In [38]:
df

Sex   Age  SibSp     Fare  Survived
0      male  22.0      1   7.2500         0
1    female  38.0      1  71.2833         1
2    female  26.0      0   7.9250         1
3    female  35.0      1  53.1000         1
4      male  35.0      0   8.0500         0
..      ...   ...    ...      ...       ...
886    male  27.0      0  13.0000         0
887  female  19.0      0  30.0000         1
888  female   NaN      1  23.4500         0
889    male  26.0      0  30.0000         1
890    male  32.0      0   7.7500         0

[891 rows x 5 columns]

In [40]:
df.drop(['SibSp'], axis= 'columns', inplace=True)

In [41]:
df

Sex   Age     Fare  Survived
0      male  22.0   7.2500         0
1    female  38.0  71.2833         1
2    female  26.0   7.9250         1
3    female  35.0  53.1000         1
4      male  35.0   8.0500         0
..      ...   ...      ...       ...
886    male  27.0  13.0000         0
887  female  19.0  30.0000         1
888  female   NaN  23.4500         0
889    male  26.0  30.0000         1
890    male  32.0   7.7500         0

[891 rows x 4 columns]

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Sex       891 non-null    object 
 1   Age       714 non-null    float64
 2   Fare      891 non-null    float64
 3   Survived  891 non-null    int64  
dtypes: float64(2), int64(1), object(1)
memory usage: 28.0+ KB


In [44]:
df['Age'].fillna(df['Age'].median(), inplace=True)

In [45]:
df

Sex   Age     Fare  Survived
0      male  22.0   7.2500         0
1    female  38.0  71.2833         1
2    female  26.0   7.9250         1
3    female  35.0  53.1000         1
4      male  35.0   8.0500         0
..      ...   ...      ...       ...
886    male  27.0  13.0000         0
887  female  19.0  30.0000         1
888  female  28.0  23.4500         0
889    male  26.0  30.0000         1
890    male  32.0   7.7500         0

[891 rows x 4 columns]

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Sex       891 non-null    object 
 1   Age       891 non-null    float64
 2   Fare      891 non-null    float64
 3   Survived  891 non-null    int64  
dtypes: float64(2), int64(1), object(1)
memory usage: 28.0+ KB


In [47]:
x = df.drop('Survived', axis='columns')
y = df['Survived']

In [48]:
x.Sex = x.Sex.map({'male':1, 'female':0})

In [49]:
x

Sex   Age     Fare
0      1  22.0   7.2500
1      0  38.0  71.2833
2      0  26.0   7.9250
3      0  35.0  53.1000
4      1  35.0   8.0500
..   ...   ...      ...
886    1  27.0  13.0000
887    0  19.0  30.0000
888    0  28.0  23.4500
889    1  26.0  30.0000
890    1  32.0   7.7500

[891 rows x 3 columns]

In [50]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y)

In [51]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(x_train, y_train)

MultinomialNB()

In [55]:
model.predict([[3,1,23]])

C:\Users\rohit\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but MultinomialNB was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

In [56]:
model.predict([[1,15,50]])

C:\Users\rohit\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but MultinomialNB was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

In [58]:
inputs =[4,7,9,3]
weights =[0.4, 0.7, 0.82, 0.25]
bias =2
output = inputs[0]*weights[0]+inputs[1]*weights[1]+inputs[2]*weights[2]+inputs[3]*weights[3]+bias

In [59]:
output

16.63

### array & matrices

In [60]:
import numpy as np

In [61]:
input = np.array([[0,0],[0,1],[1,1],[1,0]])
input

array([[0, 0],
       [0, 1],
       [1, 1],
       [1, 0]])

In [62]:
input.shape

(4, 2)

In [63]:
output= np.array([0,1,1,0])

In [64]:
output.reshape(4,1)

array([[0],
       [1],
       [1],
       [0]])

In [65]:
weights = np.array([[0.1],[0.2]])
weights

array([[0.1],
       [0.2]])

In [66]:
bias =0.3

In [67]:
#activation fuction

# sigmoid function

def sigmoid_f(x):
    return 1/(1+np.exp(-x))

In [68]:
def der_f(x):
    return sigmoid_f(x) *(1-sigmoid_f(x))

In [72]:
for epochs in range(100):
    i = input
    w_s = np.dot(i*weights)+bias
    o_1 = sigmoid_f(w_s)

    error = o_1 -o
    f_d = error
    o2 = der(f_d)

ValueError: operands could not be broadcast together with shapes (4,2) (2,1) 